version: '3.8'
services:
  postgres:
    image: postgis/postgis:13-master
    environment:
      - POSTGRES_DB=file_upload
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432